name: Check Clean Notebooks

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  check_clean_notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure clean notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
