name: Clean Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clean_notebooks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Ensure that the notebooks are clean
    - name: Ensure notebooks are clean
      uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

